In [7]:
import pandas as pd
import numpy as np

from pathlib import Path

base_root = Path(".").resolve().parents[0]
print(f"Base: {base_root}")
data_root = base_root / "input" / "petfinder-pawpularity-score"

train = pd.read_csv(data_root / "train.csv")

Base: /content/drive/MyDrive/kaggle/petfinder

In [9]:
import IPython.display as ipd

ipd.display(train.head())
ipd.display(train.describe())
ipd.display(train.info())

                                 Id  Subject Focus  ...  Blur  Pawpularity
0  0007de18844b0dbbb5e1f607da0606e0              0  ...     0           63
1  0009c66b9439883ba2750fb825e1d7db              0  ...     0           42
2  0013fd999caf9a3efe1352ca1b0d937e              0  ...     0           28
3  0018df346ac9c1d8413cfcc888ca8246              0  ...     0           15
4  001dc955e10590d3ca4673f034feeef2              0  ...     0           72

[5 rows x 14 columns]

       Subject Focus         Eyes  ...         Blur  Pawpularity
count    9912.000000  9912.000000  ...  9912.000000  9912.000000
mean        0.027643     0.772599  ...     0.070420    38.039044
std         0.163957     0.419175  ...     0.255866    20.591990
min         0.000000     0.000000  ...     0.000000     1.000000
25%         0.000000     1.000000  ...     0.000000    25.000000
50%         0.000000     1.000000  ...     0.000000    33.000000
75%         0.000000     1.000000  ...     0.000000    46.000000
max         1.000000     1.000000  ...     1.000000   100.000000

[8 rows x 13 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9912 entries, 0 to 9911
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             9912 non-null   object
 1   Subject Focus  9912 non-null   int64
 2   Eyes           9912 non-null   int64
 3   Face           9912 non-null   int64
 4   Near           9912 non-null   int64
 5   Action         9912 non-null   int64
 6   Accessory      9912 non-null   int64
 7   Group          9912 non-null   int64
 8   Collage        9912 non-null   int64
 9   Human          9912 non-null   int64
 10  Occlusion      9912 non-null   int64
 11  Info           9912 non-null   int64
 12  Blur           9912 non-null   int64
 13  Pawpularity    9912 non-null   int64
dtypes: int64(13), object(1)
memory usage: 1.1+ MB

None